[package]
cairo-version = "=2.8.4"
edition = "2024_07"
description = "The Sai Core library for autonomous worlds."
name = "sai"
version = "1.0.7"

[dependencies]
starknet = "=2.8.4"

[dev-dependencies]
cairo_test = "=2.8.4"

[lib]

[[target.starknet-contract]]
sierra = true
